---
- name: Deploy Hello World Website
  hosts: web
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy Hello World page
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Hello World from Terraform + Ansible!</h1>"
