name: Run Ansible Playbook

on:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed

jobs:
  ansible:
    runs-on: [self-hosted, gh-runner]

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download Terraform outputs
      - name: Download Terraform Outputs
        uses: actions/download-artifact@v3
        with:
          name: terraform-output
          path: ./terraform

      # Setup Python for Ansible
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install Ansible
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3

      # Setup SSH Key
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/deployer_key
          chmod 600 ~/.ssh/deployer_key
          # Fetch the Elastic IP from Terraform output JSON
          WEB_EIP=$(jq -r '.web_eip.value' ./terraform/tf_output.json)
          ssh-keyscan -H $WEB_EIP >> ~/.ssh/known_hosts

      # Run Ansible playbook
      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
